// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vpraxaahneurntlkwegw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwcmF4YWFobmV1cm50bGt3ZWd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDAwNjQsImV4cCI6MjA2NTU3NjA2NH0.wNn-GXQId3AinUF3inDUkUoqf0_ZXo3VnggwfYUJ3Ow";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);